[package]
name = "wde-terrain-grid"
version = "0.1.0"
edition = "2024"

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-terrain = { path = "../wde-terrain" }
wde-gizmos = { path = "../../render/wde-gizmos" }
wde-renderer = { path = "../../core/wde-renderer" }
wde-physics = { path = "../../wrappers/wde-physics" }
wde-camera = { path = "../../render/wde-camera" }
wde-gltf = { path = "../../render/wde-gltf" }
wde-pbr = { path = "../../render/wde-pbr" }
wde-editor = { path = "../../core/wde-editor" }
wde-scene = { path = "../../core/wde-scene" }
bevy = { workspace = true }
bytemuck = { workspace = true }
