[package]
name = "wde-wgpu"
version = "0.1.0"
authors = ["MecanicaScience"]
edition = "2024"

[dependencies]
wde-logger = { path = "../wde-logger" }
wgpu = { version = "27", features = [ "serde" ] }
futures-lite = "2.6"
bevy = { workspace = true }
serde = { workspace = true }
bytemuck = { workspace = true}

[features]
default = []
gpu-debug = []
