[workspace]
members = [
    "src",
    "examples",
    "crates/core/*",
    "crates/render/*",
    "crates/scene/*",
    "crates/wde/"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0" }
bytemuck = { version = "1.24" }
bevy = { version = "0.17", default-features = false, features = [ "multi_threaded", "bevy_asset", "bevy_window", "bevy_winit", "x11", "bevy_log", "trace_tracy" ] }
