[package]
name = "wde-wgpu"
version = "0.1.0"
authors = ["MecanicaScience"]
edition = "2024"
description = "WaterDropEngine's wgpu wrapper crate"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wgpu = { version = "22.1", features = [ "serde" ] }
bytemuck = { version = "1.12" }

[dependencies.bevy]
version = "0.17"
default-features = false
features = [
    "multi_threaded",
    "bevy_window",
    "bevy_log"
]
