[package]
name = "wde-editor"
version = "0.1.0"
edition = "2024"
description = "Editor logic for WaterDropEngine."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-renderer = { path = "../../core/wde-renderer" }
wde-logger = { path = "../../wrappers/wde-logger" }
wde-egui = { path = "../../wrappers/wde-egui" }
bevy = { workspace = true }
puffin_egui = { git = "https://github.com/explorablescience/puffin.git", rev = "56ece9e" }
