[package]
name = "wde-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
wde-renderer = { path = "../../core/wde-renderer" }
wde-logger = { path = "../../wrappers/wde-logger" }
wde-egui = { path = "../../wrappers/wde-egui" }
bevy = { workspace = true }
puffin_egui = { git = "https://github.com/explorablescience/puffin.git", rev = "56ece9e" }
