[package]
name = "wde-examples"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bevy = { workspace = true }
bytemuck = { workspace = true }
wde = { path = "../crates/wde" }

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"

[features]
default = []
remote = ["wde/remote"]
watch = ["wde/watch"]
trace = ["wde/trace"]
