[package]
name = "wde-pbr"
version = "0.1.0"
edition = "2024"
description = "Physically based rendering for WaterDropEngine."

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-renderer = { path = "../../core/wde-renderer" }
wde-camera = { path = "../wde-camera" }
wde-editor = { path = "../../core/wde-editor" }
bevy = { workspace = true }
bytemuck = { workspace = true }
uuid = "1.23"

[features]
default = ["atmosphere"]
atmosphere = []
