[package]
name = "wde-terrain"
version = "0.1.0"
edition = "2024"

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-renderer = { path = "../../core/wde-renderer" }
wde-camera = { path = "../../render/wde-camera" }
wde-pbr = { path = "../../render/wde-pbr" }
wde-gizmos = { path = "../../render/wde-gizmos" }
wde-physics = { path = "../../wrappers/wde-physics" }
bevy = { workspace = true }
bytemuck = { workspace = true }
png = { workspace = true }
