[package]
name = "wde-physics"
version = "0.1.0"
edition = "2024"
description = "The physics module for WaterDrop Engine, providing physics simulation and collision detection."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-camera = { path = "../../render/wde-camera" }
bevy = { workspace = true }
rapier3d = { version = "0.23", default-features = false, features = [ "dim3", "f32", "parallel", "simd-stable", "serde-serialize" ] }
