[package]
name = "wde"
version = "0.1.0"
edition = "2024"
description = "WaterDropEngine - A modular game engine written in Rust."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-renderer = { path = "../render/wde-renderer" }
wde-wgpu = { path = "../core/wde-wgpu" }
wde-scene = { path = "../scene/wde-scene" }
wde-gizmos = { path = "../render/wde-gizmos", optional = true }
bevy = { workspace = true }

[features]
default = []
remote = ["bevy/bevy_remote"]
watch = ["bevy/file_watcher", "wde-renderer/watch"]
trace = ["bevy/trace_tracy_memory", "wde-renderer/trace"]
gizmos = ["wde-gizmos"]
