[package]
name = "wde-scene"
version = "0.1.0"
edition = "2024"
description = "High-level scene management for WaterDropEngine."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-logger = { path = "../../core/wde-logger" }
wde-wgpu = { path = "../../core/wde-wgpu" }
wde-renderer = { path = "../../render/wde-renderer" }
wde-pbr = { path = "../../render/wde-pbr" }
wde-camera = { path = "../../render/wde-camera" }
wde-gizmos = { path = "../../render/wde-gizmos" }
wde-gltf = { path = "../wde-gltf" }
wde-physics = { path = "../wde-physics" }
bevy = { workspace = true }
serde = { workspace = true }
bytemuck = { workspace = true }
rapier3d = { version = "0.23", default-features = false, features = [ "dim3", "f32", "parallel", "simd-stable", "serde-serialize" ] }
serde_json = "1.0"
