[package]
name = "wde-renderer-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
bevy = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
toml_edit = { version = "0.25.1", default-features = false, features = [ "parse" ] }
