[package]
name = "wde-terrain-terraform"
version = "0.1.0"
edition = "2024"
description = "The terrain terraforming module for WaterDrop Engine."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-renderer = { path = "../../core/wde-renderer" }
wde-camera = { path = "../../render/wde-camera" }
wde-pbr = { path = "../../render/wde-pbr" }
wde-gizmos = { path = "../../render/wde-gizmos" }
wde-physics = { path = "../../wrappers/wde-physics" }
wde-terrain = { path = "../wde-terrain" }
bevy = { workspace = true }
