[package]
name = "wde-renderer"
version = "0.1.0"
edition = "2024"
description = "High-level rendering logic for WaterDropEngine."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-wgpu = { path = "../../wrappers/wde-wgpu" }
bevy = { workspace = true }
serde = { workspace = true }
bytemuck = { workspace = true }
thiserror = "1.0"
tobj = "4.0"
async-channel = "2.3"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[features]
default = []
editor = []
