[package]
name = "wde"
version = "0.1.0"
edition = "2024"
description = "WaterDropEngine - A modular game engine written in Rust."

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
wde-logger = { path = "../../wrappers/wde-logger" }
wde-renderer = { path = "../wde-renderer" }
wde-camera = { path = "../../render/wde-camera" }
wde-camera-controller = { path = "../../render/wde-camera-controller" }
wde-gltf = { path = "../../render/wde-gltf" }
wde-physics = { path = "../../wrappers/wde-physics" }
wde-terrain = { path = "../../terrain/wde-terrain" }
wde-terrain-grid = { path = "../../terrain/wde-terrain-grid" }
wde-terrain-editor = { path = "../../terrain/wde-terrain-editor" }
wde-terrain-navigation = { path = "../../terrain/wde-terrain-navigation" }
wde-scene = { path = "../wde-scene" }
wde-gizmos = { path = "../../render/wde-gizmos", optional = true }
wde-pbr = { path = "../../render/wde-pbr", optional = true }
wde-editor = { path = "../wde-editor", optional = true }
bevy = { workspace = true }

[features]
default = ["pbr", "gizmos"]
gizmos = ["wde-gizmos"]
pbr = ["wde-pbr"]
watch = ["bevy/file_watcher"]
tracing = ["wde-logger/tracing", "bevy/trace_tracy_memory", "wde-logger/puffin"]
editor = ["wde-editor", "wde-renderer/editor", "wde-logger/editor"]
