[package]
name = "wde-game"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bevy = { workspace = true }
bytemuck = { workspace = true }

[dependencies.wde]
version = "0.1.0"
path = "../crates/wde"
features = [
    "gizmos"
]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"

[features]
default = []
remote = ["wde/remote"]
watch = ["wde/watch"]
trace = ["wde/trace"]
