[package]
name = "wde-game"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bevy = { workspace = true }
bytemuck = { workspace = true }

[target.'cfg(debug_assertions)'.dependencies]
bevy = { workspace = true, features = [ "debug" ] }

[dependencies.wde]
path = "../crates/core/wde"
features = [
    "editor"
]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"

[features]
default = []
watch = ["wde/watch"]
tracing = ["wde/tracing"]
x11 = ["bevy/x11"]
wayland = ["bevy/wayland"]
gpu-debug = ["wde/gpu-debug"]
