[package]
name = "waterdropengine"
version = "0.1.0"
edition = "2024"
authors = ["ExplorableScience <explorablescience@gmail.com>"]
homepage = "https://explorablescience.com"
build = "build.rs"

[dependencies]
bevy = { workspace = true }
bytemuck = { workspace = true }

[dependencies.wde]
path = "../crates/core/wde"
features = [
    "editor"
]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"

[features]
default = []
log-debug = ["wde/log-debug"]
debug = ["wde/debug"]
watch = ["wde/watch"]
tracing = ["wde/tracing"]
gpu-debug = ["wde/gpu-debug"]
