[package]
name = "wde-physics"
version = "0.1.0"
edition = "2024"

[dependencies]
wde-logger = { path = "../wde-logger" }
wde-camera = { path = "../../render/wde-camera" }
bevy = { workspace = true }
rapier3d = { version = "0.23", default-features = false, features = [ "dim3", "f32", "parallel", "simd-stable", "serde-serialize" ] }
